### ISSUE TITLE
Add remove command

### ISSUE THREAD

**Issue by c-crit-fugue** [crit/conduct#2]
Proposed new command:

`conduct opa remove case aws.security_groups.ingress_5900 validNoIngress5900`

- remove `aws/security_groups/cases/valid_no_ingress_5900.tf`
- remove `validNoIngress5900` from `aws/security_groups/ingress_5900_test_input.rego`
- remove `valid_no_ingress_5900` from `aws/security_groups/ingress_5900_test.rego`

**Comment by crit** [comment]
fixed by 6e9d873e88c2f909de447991a2bd0d5a3b4b8493
